postgres1:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: '123456'
      port: 2345
      dbname: postgres # or database instead of dbname
      schema: public
      threads: 10
      connect_timeout: 10 # default 10 seconds
